# Configuration file for ${project.name} ${project.version}

# Global placeholders can be added here.
# Global placeholders DO NOT support built-in placeholders.
placeholders:
  _placeholder: "replacement"

# ===================================================================================================================#
#                                               Placeholder Information                                              #
#    Placeholders are pieces of text that will be automatically replaced by the plugin with the appropriate value.  #
#    The following placeholders are available for use in a SCOREBOARD LINE:                                          #
#    ______________________________________________________________________________________________________________  #
#    | Placeholder             | Description                                                                      |  #
#    ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾  #
#    - %timer%                  Replaced by the Biathlon instance's timer.                                           #
#    - %playersFinished%        Replaced by the number of players that have reached the finish.                      #
#    - %playersNotFinished%     Replaced by the number of players that have not yet finished the game. Ex: 3/20      #
#    - %playersParticipating%   Replaced by the total number of players participating in the game.                   #
#    - %shootings%              Replaced by the number of shootings in the game.                                     #
#    - %header%                 Replaced by a user-defined header under 'defaults'.                                  #
#    - %footer%                 Replaced by a user-defined footer under 'defaults'.                                  #
#    - %date%                   *Replaced by the local date (ex: 22/05/2023).                                        #
#    - %dateTime%               *Replaced by the local date and time (ex: 22/05/2023 14:33:20).                      #
#    - %localTime%              *Replaced by the local time (ex: 14:33:20).                                          #
#    - %state%                  Replaced by the internal game status (ex: STANDBY).                                  #
#    - global placeholders      Replaced by the values configured under 'placeholders'                               #
#                                                                                                                    #
#     * these values have configurable formats under 'options'                                                       #
#                                                                                                                    #
#                                                                                                                    #
#    The following placeholders are available for use in the SCOREBOARD TITLE:                                       #
#    ______________________________________________________________________________________________________________  #
#    | Placeholder             | Description                                                                      |  #
#    ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾  #
#    - %timer%                  Replaced by the Biathlon instance's timer.                                           #
#    - %state%                  Replaced by the internal game status (ex: STANDBY).                                  #
#    - %title%                  Replaced by the game's display name.                                                 #
# ===================================================================================================================#

# ===================================================================================================================#

# General Settings
options:

  # %date%
  date-format: "dd/MM/yyyy"

  # %dateTime%
  date-format-full: "dd/MM/yyyy hh:mm:ss"

  # In-game timer format (%timer%)
  timer-format: "hh:mm:ss"

  # Scoreboard clock format (%localTime%)
  time-format: "hh:mm:ss"

  # Controls whether the target player of a game event should be also notified about their actions.
  # Example: if this property is TRUE, then when a player passes a checkpoint, everyone **including** the player
  #          receives a message, that they have passed a checkpoint.
  #          if this property is FALSE, then when a player passes a checkpoint, everyone **but** the player will
  #          be notified that they've passed a checkpoint.
  exclude-target-player-from-event-notification: false

  # Controls whether the instance status changes (e.g "PAUSED -> RUNNING") should be sent
  # to the player that started the game.
  notify-instance-status-change: true


# Plugin defaults
defaults:
  # Default scoreboard config (ID: "default")
  scoreboardconfig:
    title: "%title%"
    line1: "%header%"
    line2: "&bPlayers to finish: &e%playersNotFinished%"
    line3: "&bTotal players: &e%playersParticipating%"
    line4: "&6Shootings: &e%shootings%"
    line5: "&bDate: &e%date%"
    line6: "&bGame Duration: &e%timer%"
    line7: "&fStatus: &l%state%"
    line8: "%footer%"
  footer: "&e========================"
  header: "&e========================"
# ===================================================================================================================#
