# Configuration file for ${project.name} ${project.version}

# ===================================================================================================================#
#                                                ABOUT PLACEHOLDERS                                                  #
#    Placeholders are pieces of text that will be automatically replaced by the plugin with the appropriate value.   #
#    The following placeholders are available for use in a SCOREBOARD LINE:                                          #
#    ______________________________________________________________________________________________________________  #
#    | Placeholder             | Description                                                                      |  #
#    ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾  #
#    - %timer%                  Replaced by the Biathlon instance's timer.                                           #
#    - %playersFinished%        Replaced by the number of players that have reached the finish.                      #
#    - %playersNotFinished%     Replaced by the number of players that have not yet finished the game. Ex: 3/20      #
#    - %playersParticipating%   Replaced by the total number of players participating in the game.                   #
#    - %shootings%              Replaced by the number of shootings in the game.                                     #
#    - %header%                 Replaced by a user-defined header under 'defaults'.                                  #
#    - %footer%                 Replaced by a user-defined footer under 'defaults'.                                  #
#    - %date%                   *Replaced by the local date (ex: 22/05/2023).                                        #
#    - %dateTime%               *Replaced by the local date and time (ex: 22/05/2023 14:33:20).                      #
#    - %localTime%              *Replaced by the local time (ex: 14:33:20).                                          #
#    - %state%                  Replaced by the internal game status (ex: STANDBY).                                  #
#    - %bestTime%               Replaced by [first-finished-player] - [time] or 'N/A' if no best time is available.  #
#    - global placeholders      Replaced by the values configured under 'placeholders'                               #
#                                                                                                                    #
#     * these values have configurable formats under 'options'                                                       #
#                                                                                                                    #
#                                                                                                                    #
#    The following placeholders are available for use in the SCOREBOARD TITLE:                                       #
#    ______________________________________________________________________________________________________________  #
#    | Placeholder             | Description                                                                      |  #
#    ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾  #
#    - %timer%                  Replaced by the Biathlon instance's timer.                                           #
#    - %state%                  Replaced by the internal game status (ex: STANDBY).                                  #
#    - %title%                  Replaced by the game's display name.                                                 #
# ===================================================================================================================#



# ===================================================================================================================#
#                                               GLOBAL PLACEHOLDERS                                                  #
#                             * global placeholders do not support built-in placeholders                             #
# ===================================================================================================================#

placeholders:
  _placeholder: "replacement"

# ===================================================================================================================#


# ===================================================================================================================#
#                                               GENERAL OPTIONS                                                      #
# ===================================================================================================================#
options:

  # ===================================================================================================================#
  #                                               FORMAT OPTIONS                                                       #
  #                               * Keep in mind: time formats are case sensitive                                      #
  # ===================================================================================================================#

  # __________________________________________________________________________________________________________________ #
  # | Setting                             | Placeholder          | Description                                       | #
  # ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾ #
  date-format: "dd/MM/yyyy"               # %date%                Generic date
  date-format-full: "dd/MM/yyyy hh:mm:ss" # %dateTime%            Date and time
  timer-format: "hh:mm:ss"                # %timer%               In-game timer format
  time-format: "hh:mm:ss"                 # %localTime%           Clock format


  # ===================================================================================================================#
  #                                            GAME PROCESS SETTINGS                                                   #
  # ===================================================================================================================#

  # Controls whether the instance status changes (e.g "PAUSED -> RUNNING") should be sent to the player that
  # started the game.
  notify-instance-status-change: false

  # Should the game be paused if a player that is participating disconnects?
  # If set to true, a countdown will start counting down from [delay], after which the game will be paused.
  pause-if-player-disconnect:
    state: true
    delay: 5

  # Automatically return disconnected players to the game upon reconnecting
  # If set to false, players can still rejoin using /rejoin
  autorejoin: true

  # Should players be given a maximum level slowness effect as to halt them when the final countdown starts?
  halt-players-with-effect: true

  # Enable sound effects?
  sound-effects: true

  scoreboards:
    enable-shooting-range: true
    enable-leaderboard: true

  # How long should a scoreboard stay on screen before the next type is shown (e.g. Shooting Range, Leaderboard)
  scoreboard-cycle-period: 15

  # Should BiaMine generate a game report file?
  # %dataFolder% will generate the report file in plugins/BiaMine-Reloaded/
  game-report:
    enabled: true
    path: "%dataFolder%"


# ===================================================================================================================#
#                                               MESSAGE SETTINGS                                                     #
# ===================================================================================================================#
notification-settings:

  # This section contains settings for various settings the plugin sends out.
  # Change value after 'enabled' to either false, to disable this message, or true, to enable it.
  # You may also change the target of those messages. Valid settings for 'target' are: all, player
  # 'all' => send to everyone
  # 'player' => send to message target

  player-finished:
    enabled: true
    target: all

  checkpoint-reached:
    enabled: true
    target: all

  target-hit:
    enabled: true
    target: all

  new-lap:
    enabled: true

  shooting-spot-claim:
    enabled: true

  shooting-spot-exit:
    enabled: true
    target: all


# ===================================================================================================================#
#                                               PLUGIN DEFAULTS                                                      #
# ===================================================================================================================#

defaults:
  # Default scoreboard config (ID: "default")
  scoreboardconfig:
    title: "%title%"
    line1: "%header%"
    line2: "&bPlayers to finish: &e%playersNotFinished%"
    line3: "&bTotal players: &e%playersParticipating%"
    line4: "&bShootings: &e%shootings%"
    line5: "&bDate: &e%date%"
    line6: "&bGame Duration: &e%timer%"
    line7: "&fStatus: %state%"
    line8: "%footer%"
  footer: "&e========================"
  header: "&e========================"
# ===================================================================================================================#
