package krisapps.biaminereloaded.types;

public enum ConfigProperty {
    HEADER_CONTENT,
    FOOTER_CONTENT,
    TIMER_FORMAT,
    DATE_FORMAT,
    DATE_FORMAT_EXTENDED,
    TIME_FORMAT,
    EXCLUDE_TARGET_PLAYER_FROM_CHECKPOINT_MESSAGE,
    NOTIFY_STATUS_CHANGE,
    PAUSE_IF_PLAYER_DISCONNECT,
    EMERGENCY_PAUSE_DELAY,
    AUTOREJOIN,
    HALT_PLAYERS_WITH_POTIONEFFECT,
    SEND_ITEM_DISPENSER_MESSAGES,
    GAME_REPORT_PATH,
    GENERATE_GAME_REPORT
}
