package krisapps.biaminereloaded.types;

public enum ConfigProperty {
    HEADER_CONTENT,
    FOOTER_CONTENT,
    TIMER_FORMAT,
    DATE_FORMAT,
    DATE_FORMAT_EXTENDED,
    TIME_FORMAT,
    EXCLUDE_TARGET_PLAYER_FROM_CHECKPOINT_MESSAGE,
    NOTIFY_STATUS_CHANGE,
}
