package krisapps.biaminereloaded.types.config;

public enum ConfigProperty {
    HEADER_CONTENT,
    FOOTER_CONTENT,
    TIMER_FORMAT,
    DATE_FORMAT,
    DATE_FORMAT_EXTENDED,
    TIME_FORMAT,
    NOTIFY_STATUS_CHANGE,
    PAUSE_IF_PLAYER_DISCONNECT,
    EMERGENCY_PAUSE_DELAY,
    AUTOREJOIN,
    HALT_PLAYERS_WITH_POTIONEFFECT,
    SEND_ITEM_DISPENSER_MESSAGES, SCOREBOARD_CYCLE_PERIOD, SHOOTING_RANGE_SCOREBOARD_ENABLED, LEADERBOARD_ENABLED,
}
